Explore target
DeepRank/deeprank-core pull request #199
Opened 2022-09-29 09:58 UTC by DaniBodor

- moved `task` parameter from `NeuralNet` to `HDF5DataSet`, so that it is in the same class as `target`
- as task options, I changed "class" and "reg" to "classif" and "regress", which to me are clearer
- added some linting to NeuralNet class

2022-09-29 10:54 UTC, DaniBodor commented
For some reason all tests in test_nn.py and test_integration.py are failing with a message 

> AttributeError: 'NeuralNet' object has no attribute 'task'

I don't understand why this is happening. As far as I see, it doesn't try to assign a `task` to the NeuralNet objects, only to the HDF5DataSet objects.

2022-09-29 20:08 UTC, DaniBodor commented
I think this is going to have a bunch of conflicts with #196 (am still in the process of reviewing that).
What is the best way to go forward?

2022-09-30 13:22 UTC, gcroci2 commented on docs/quickstart.md
> +from deeprankcore.NeuralNet import NeuralNet
I think that `from deeprankcore.DataSet import save_hdf5_keys` should stay and lines from 70 to 99 should be deleted (see below, HDF5DataSet and NeuralNet objects are initialized there)

2022-09-30 13:24 UTC, gcroci2 requested changes
Everything is fine, except in the readme we need to add the new task parameter in the HDF5DataSet objects

2022-10-03 13:25 UTC, closed without merging

2022-10-03 13:25 UTC, DaniBodor commented
Replaced by @200