fix: Improve indexing of hdf5 files
DeepRank/deeprank-core pull request #362
Opened 2023-02-15 15:30 UTC by joyceljy

2023-02-20 10:29 UTC, gcroci2 requested changes
Few notes:
- I see some edits (such as line 376 in dataset.py and lines 295-306 in utils/graph.py) which are on the main branch but appear on your PR. If you branched from main (after having pulled the last version of it doing `git pull`) this shouldn't be happening. 
- Please remember to delete deeprankcore/tools/plotgraph.py file, which is empty.
- List comprehension should speed up the process, but to be sure and to have some more precise timings you can use [cProfile](https://www.machinelearningplus.com/python/cprofile-how-to-profile-your-python-code/) module and then report the comparison between running `_create_index_entries` method before and after your changes. You could add such considerations on the [issue](https://github.com/DeepRank/deeprank-core/issues/340). To see an example about how to use the module, see [here](https://github.com/DeepRank/3D-Vac/blob/0372cadd9db7a695d901b6829ccc0fa31ccf8bcd/src/4_train_models/GNN/I/classification/struct/training.py#L237). You could enable cprofiler inside the `_create_index_entries` method and log the timings there before and after your changes, using the 100 samples example dataset I gave you.

2023-02-20 10:29 UTC, gcroci2 commented on deeprankcore/dataset.py
> +                         if self.target_filter is None or self._filter_targets(hdf5_file[entry_name]) is True]
```suggestion
                         if self._filter_targets(hdf5_file[entry_name])]
```

2023-02-21 13:30 UTC, joyceljy commented
[cProfileTestResult.zip](https://github.com/DeepRank/deeprank-core/files/10793905/cProfileTestResult.zip)
I tested the performance time of the new index code using cProfile with 100 sample data.
From the cumulative time, there was a 2-sec improvement for per call in dataset.py.
The comparison result is in the attached file, the file name with _old is the performance result using the original code

2023-02-22 09:37 UTC, gcroci2 requested changes
plotgraph.py needs to be in tools/, not tools/visualization/ :)

2023-02-22 09:42 UTC, gcroci2 commented
> [cProfileTestResult.zip](https://github.com/DeepRank/deeprank-core/files/10793905/cProfileTestResult.zip) I tested the performance time of the new index code using cProfile with 100 sample data. From the cumulative time, there was a 2-sec improvement for per call in dataset.py. The comparison result is in the attached file, the file name with _old is the performance result using the original code
> 
> Cumulative time result after index accelerating: ![image](https://user-images.githubusercontent.com/29445408/220374427-1868ed6e-26f9-4b88-b41f-5db15c636e7d.png)
> 
> Cumulative time result before index accelerating: ![image](https://user-images.githubusercontent.com/29445408/220374668-d676b853-283a-47b9-949f-e7a3b1f570cd.png)

The improvement is of 0.002 s actually, right? From the screenshots I would say this. 
Last experiment you could do, is to pass multiple times the hdf5 file to the GraphDataset object in order to use more data points and see how this scales. I would advice to use ~1000 data points to have a more indicative measure of the improvement (with 100 we can't really see if it's significative)

2023-02-22 14:19 UTC, joyceljy commented
[IndexAccerlateTestResult.zip](https://github.com/DeepRank/deeprank-core/files/10804648/IndexAccerlateTestResult.zip)
Update: 
Tested 71000 samples of data using the new index accelerating method.
The performance improved by around 8 seconds in total.
Cumulative time result after index accelerating:
![image](https://user-images.githubusercontent.com/29445408/220648129-75440854-4c75-4180-a45c-1722a80f6f32.png)

Cumulative time result before index accelerating:
![image](https://user-images.githubusercontent.com/29445408/220648231-aba1b202-b366-410b-aa87-1532dbabf542.png)

2023-02-23 07:49 UTC, gcroci2 requested changes
Please commit my suggestions, then just to be sure ask also @DaniBodor a check. If all tests pass, then feel free to merge :)

2023-02-23 07:49 UTC, gcroci2 commented on deeprankcore/dataset.py
> +                    if (self.target_filter is None):
```suggestion
                    if self.target_filter is None:
```

2023-02-23 07:49 UTC, gcroci2 commented on deeprankcore/dataset.py
> +                        self.index_entries += [(hdf5_path, entry_name) for entry_name in entry_names]
```suggestion
                        self.index_entries = [(hdf5_path, entry_name) for entry_name in entry_names]
```

2023-02-23 07:49 UTC, gcroci2 commented on deeprankcore/dataset.py
> +                        self.index_entries += [(hdf5_path, entry_name) for entry_name in entry_names \
```suggestion
                        self.index_entries = [(hdf5_path, entry_name) for entry_name in entry_names \
```

2023-02-23 10:46 UTC, DaniBodor commented
> Please commit my suggestions, then just to be sure ask also @DaniBodor a check. I removed the "+" from the list comprehension since I think it's not needed. If all tests pass, then feel free to merge :)

I believe it should actually remain `+=` (as in the original), because we are adding to the list for each `entry_name`. Otherwise we keep overwriting the list and essentially only have indices for the final entry.

2023-02-23 15:45 UTC, DaniBodor approved these changes
Looks good, Joyce!
With your changes, line 130 (`self.index_entries = []`) has become obsolete. This was needed before, because we were adding entries to the list one by one in a loop, but now with the list comprehension it all happens at once.
You can delete this line and then (if all checks pass) you can go ahead and merge to main.

Also, could you give a 1 or 2 sentence summary (or bullet points) of your changes in the top comment of this PR. That can be very useful if in the future we want to look back at this and quickly know what was changed.

2023-02-23 20:43 UTC, merged