docs: update README.md
DeepRank/deeprank-core pull request #443
Opened 2023-06-02 14:55 UTC by gcroci2

The current PyPi release does not work with the documentation we have, because the release is outdated. I'll do a new release very soon but in the meantime we need to add that to the readme

2023-06-02 16:58 UTC, DaniBodor commented
what do you mean by it doesn't work?

2023-06-05 09:24 UTC, gcroci2 commented
> what do you mean by it doesn't work?

The docs are updated with the code, but the release is old so if you pip install deeprankcore using the released version (1.0.0) and then try to follow the docs for using the package, you'll get errors and issues.

2023-06-07 09:04 UTC, DaniBodor requested changes
Maybe also remove reduce from install instructions already? Even though the other thing isn't ready to be announced yet, reduce is not useful and only gives bugs anyway and is the most tedious part of the install instructions.

2023-06-07 09:04 UTC, DaniBodor commented on README.md
> +Please note that the PyPi release is currently outdated and we will do a new release very soon. In the meantime, you can get all the new developments by cloning the repo and installing the code with
it's still unclear to me what the added value of just this statement is. If people can use the package, I don't think we need to say this. If they can't use the package right now, we shouldn't tell them to install.

If we do need to say something about it, I think it needs a bit more explanation. As a non-expert user, if I see this statement, I would have no idea what I should do now.

2023-06-07 14:41 UTC, gcroci2 commented
> Maybe also remove reduce from install instructions already? Even though the other thing isn't ready to be announced yet, reduce is not useful and only gives bugs anyway and is the most tedious part of the install instructions.

Done, I've also removed reduce from the CI, since we're not testing add_hydrogens it shouldn't break anything.

2023-06-08 09:31 UTC, DaniBodor approved these changes
awesome!

2023-06-08 09:54 UTC, merged